# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
 devices([
   "iPhone X",
   "iPhone 8",
   "iPhone 8 Plus",
   "iPhone SE",
	 "iPad Pro (12.9-inch) (2nd generation)",
 ])

languages([
  "en-US",
])

# Arguments to pass to the app on launch. See https://github.com/fastlane/snapshot#launch_arguments
# launch_arguments("-favColor red")

# The name of the scheme which contains the UI Tests
scheme "Knuff"

# Where should the resulting screenshots be stored?
# output_directory "./screenshots"

# clear_previous_screenshots # remove the '#' to clear all previously generated screenshots before creating new ones

# Choose which project/workspace to use
# project "./Project.xcodeproj"
# workspace "./Project.xcworkspace"

# For more information about all available options run
# snapshot --help
